### ISSUE TITLE
bug running in gem dev

### ISSUE THREAD

**Issue by chrismo** [livingsocial/bundler-patch#10]
```
No known vulnerabilities to update.
Updating 'bundler-fixture' conservatively.
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
/Users/chrismo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/resolver.rb:354:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'bundler-advise' in source at `.`. (Bundler::GemNotFound)
Source contains 'bundler-advise' at: 1.0.3
        from /Users/chrismo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/resolver.rb:330:in `each'
        from /Users/chrismo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/resolver.rb:330:in `verify_gemfile_dependencies_are_found!'
        from /Users/chrismo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/resolver.rb:199:in `start'
        from /Users/chrismo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-patch-0.7.2/lib/bundler/patch/conservative_definition.rb:36:in `resolve'
        from /Users/chrismo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.rb:137:in `specs'
        from /Users/chrismo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.rb:126:in `resolve_remotely!'
        from /Users/chrismo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/installer.rb:194:in `resolve_if_need'
        from /Users/chrismo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/installer.rb:69:in `run'
        from /Users/chrismo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/installer.rb:21:in `install'
        from /Users/chrismo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-patch-0.7.2/lib/bundler/patch/cli.rb:59:in `conservative_update'
        from /Users/chrismo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-patch-0.7.2/lib/bundler/patch/cli.rb:105:in `_patch'
        from /Users/chrismo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-patch-0.7.2/lib/bundler/patch/cli.rb:48:in `patch'
        from /Users/chrismo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-patch-0.7.2/lib/bundler/patch/cli.rb:26:in `execute'
        from /Users/chrismo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-patch-0.7.2/bin/bundler-patch:10:in `<top (required)>'
        from /Users/chrismo/.rbenv/versions/2.2.3/bin/bundler-patch:23:in `load'
        from /Users/chrismo/.rbenv/versions/2.2.3/bin/bundler-patch:23:in `<main>'
```

**Comment by chrismo** [comment]
was able to upgrade an internal LS gem with its gemspec, fwiw. so, not a global problem?
