### ISSUE TITLE
Support 1.11.x of Bundler

### ISSUE THREAD

**Issue by chrismo** [livingsocial/bundler-patch#5]
```
/Users/chrismo/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/resolver.rb:187:in `initialize': wrong number of arguments (3 for 4) (ArgumentError)
	from /Users/chrismo/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/bundler-patch-0.7.0/lib/bundler/patch/conservative_definition.rb:19:in `new'
	from /Users/chrismo/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/bundler-patch-0.7.0/lib/bundler/patch/conservative_definition.rb:19:in `resolve'
	from /Users/chrismo/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/definition.rb:137:in `specs'
	from /Users/chrismo/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/definition.rb:126:in `resolve_remotely!'
	from /Users/chrismo/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/installer.rb:194:in `resolve_if_need'
	from /Users/chrismo/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/installer.rb:69:in `run'
	from /Users/chrismo/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/installer.rb:21:in `install'
	from /Users/chrismo/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/bundler-patch-0.7.0/lib/bundler/patch/cli.rb:61:in `conservative_update'
	from /Users/chrismo/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/bundler-patch-0.7.0/lib/bundler/patch/cli.rb:107:in `_patch'
	from /Users/chrismo/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/bundler-patch-0.7.0/lib/bundler/patch/cli.rb:50:in `patch'
	from /Users/chrismo/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/bundler-patch-0.7.0/lib/bundler/patch/cli.rb:26:in `execute'
	from /Users/chrismo/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/bundler-patch-0.7.0/bin/bundler-patch:10:in `<top (required)>'
	from /Users/chrismo/.rbenv/versions/2.1.7/bin/bundler-patch:23:in `load'
	from /Users/chrismo/.rbenv/versions/2.1.7/bin/bundler-patch:23:in `<main>'```

**Comment by chrismo** [comment]
Fixed: 43127f44c2f12404a3c245fe0fbee158bee91ebb
